# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: rake
before:
  hooks:
    - make completion manual
builds:
  - id: linux
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - riscv64
    ldflags:
      - -X 'github.com/AppleGamer22/rake/cmd.Version={{ .Version }}'
      - -X 'github.com/AppleGamer22/rake/cmd.Hash={{ .FullCommit }}'
  - id: mac
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X 'github.com/AppleGamer22/rake/cmd.Version={{ .Version }}'
      - -X 'github.com/AppleGamer22/rake/cmd.Hash={{ .FullCommit }}'
  - id: windows
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X 'github.com/AppleGamer22/rake/cmd.Version={{ .Version }}'
      - -X 'github.com/AppleGamer22/rake/cmd.Hash={{ .FullCommit }}'
archives:
  - id: unix
    builds:
    - linux
    - mac
    replacements:
      darwin: mac
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - rake.bash
      - rake.fish
      - rake.zsh
      - rake.1
  - id: windows
    builds:
      - windows
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - rake.ps1
      - rake.1
nfpms:
  - package_name: rake
    vendor: AppleGamer22
    maintainer: Omri Bornstein <omribor@gmail.com>
    homepage: https://github.com/AppleGamer22/rake
    license: GPL-3.0
    description: Cross-platform caffeinate alternative.
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - linux
    dependencies:
      - dbus
    formats:
      - apk
      - deb
      - rpm
    contents:
      - src: rake.1
        dst: /usr/share/man/man1/rake.1
      - src: rake.bash
        dst: /usr/share/bash-completion/completions/rake
      - src: rake.fish
        dst: /usr/share/fish/completions/rake.fish
      - src: rake.zsh
        dst: /usr/share/zsh/site-functions/_rake
changelog:
  use: github
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^chore'
    - typo
    - Merge pull request
    - Merge remote-tracking branch
    - Merge branch
    - go mod tidy
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999
release:
  github:
    owner: AppleGamer22
    name: rake
  discussion_category_name: General
  footer: |
    ## Installation
    ### Arch Linux Distributions
    * [`yay`](https://github.com/Jguer/yay):
    ```bash
    yay -S rake-bin
    ```
    * [`paru`](https://github.com/morganamilo/paru):
    ```bash
    paru -S rake-bin
    ```

    ### macOS
    * [Homebrew Tap](https://github.com/AppleGamer22/homebrew-rake):
    ```bash
    brew install AppleGamer22/tap/rake
    ```
  prerelease: auto
aurs:
  - homepage: https://github.com/AppleGamer22/rake
    description: Cross-platform caffeinate alternative.
    license: GPL3
    maintainers:
      - Omri Bornstein <omribor@gmail.com>
    contributors:
      - Omri Bornstein <omribor@gmail.com>
    private_key: "{{ .Env.AUR_SSH_PRIVATE_KEY }}"
    git_url: ssh://aur@aur.archlinux.org/rake-bin.git
    depends:
      - dbus
    optdepends:
      - bash
      - fish
      - zsh
    package: |
      install -Dm755 rake "${pkgdir}/usr/bin/rake"
      install -Dm644 rake.1 "${pkgdir}/usr/share/man/man1/rake.1"
      install -Dm644 rake.bash "${pkgdir}/usr/share/bash-completion/completions/rake"
      install -Dm644 rake.fish "${pkgdir}/usr/share/fish/vendor_completions.d/rake.fish"
      install -Dm644 rake.zsh "${pkgdir}/usr/share/zsh/site-functions/_rake"
    commit_author:
      name: Omri Bornstein
      email: omribor@gmail.com
brews:
  - tap:
      owner: AppleGamer22
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    download_strategy: CurlDownloadStrategy
    commit_author:
      name: Omri Bornstein
      email: omribor@gmail.com
    homepage: https://github.com/AppleGamer22/rake
    description: Cross-platform caffeinate alternative.
    license: GPL-3.0
    install: |
      bin.install "rake"
      man1.install "rake.1"
      bash_completion.install "rake.bash" => "rake"
      fish_completion.install "rake.fish"
      zsh_completion.install "rake.zsh" => "_rake"