name: Test
on:
  pull_request:
    types:
      - opened
      - closed
      - reopened
  workflow_dispatch:
    inputs: {}
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{matrix.os}}
    steps:
      - name: Pull Source Code
        uses: actions/checkout@v3
      # - name: Install Linux-only Dependencies
      #   if: matrix.os == 'ubuntu-latest'
      #   run: |
      #     # sudo apt install -y ubuntu-desktop-minimal
      #     # sudo systemctl isolate graphical
      #     # sudo systemctl start gdm3
      - name: Set-up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18.3"
      - name: Test
        run: make test
  dependency_review:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Pull Source Code
        uses: actions/checkout@v3
      - name: Set-up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18.3"
      - name: Dependency Review
        uses: actions/dependency-review-action@v2
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: go
      - name: Build
        run: go build -race ./server
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2